### ISSUE TITLE
Is it similar to Cordova (hybrid application) or ReactNative framework?

### ISSUE THREAD

**Issue by peratik** [android-js/androidjs-builder#9]
Hello

Is it similar to Cordova (hybrid application, WebView) or ReactNative framework?

Thank you

**Comment by Chhekur** [comment]
It is different from both,
different from Cordova because `Android JS` allows you to wrote code in Node JS, so you can use any NPM packages in your app but there is no such kind of facility in Cordova, Cordova is just for front end only.

different from ReactNative because ReactNative also provide front end only, if you want to create server then you have to deploy it some where else and have to fetch data from API's in your app but `Android JS` provides Node JS runtime environment so you can build express server or whatever you want inside your app no need to deploy it on server.
